[package]
name = "riscv-core"
version = "3.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libc = "0.2"

[features]
always-trace = []

[dev-dependencies]
proptest = "1.4"
mockall = "0.13"
pretty_assertions = "1.4"
rstest = "0.23"
env_logger = "0.11"
log = "0.4"

[build-dependencies]
which = "6"
